[package]
name = "identity-client"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2018"

[dependencies]
failure = "0.1"
futures = "0.1"
hyper = "0.12"
log = "0.4"
percent-encoding = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
