/*
 * Identity Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-02-02
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IdentityList {
    #[serde(rename = "identities")]
    identities: Vec<crate::models::IdentityResult>,
}

impl IdentityList {
    pub fn new(identities: Vec<crate::models::IdentityResult>) -> IdentityList {
        IdentityList {
            identities: identities,
        }
    }

    pub fn set_identities(&mut self, identities: Vec<crate::models::IdentityResult>) {
        self.identities = identities;
    }

    pub fn with_identities(
        mut self,
        identities: Vec<crate::models::IdentityResult>,
    ) -> IdentityList {
        self.identities = identities;
        self
    }

    pub fn identities(&self) -> &Vec<crate::models::IdentityResult> {
        &self.identities
    }
}
