/* 
 * Identity Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-02-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IdentitySpec {
  #[serde(rename = "name", skip_serializing_if="Option::is_none")]
  name: Option<String>,
  #[serde(rename = "managedBy", skip_serializing_if="Option::is_none")]
  managed_by: Option<String>
}

impl IdentitySpec {
  pub fn new() -> IdentitySpec {
    IdentitySpec {
      name: None,
      managed_by: None
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> IdentitySpec {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

  pub fn set_managed_by(&mut self, managed_by: String) {
    self.managed_by = Some(managed_by);
  }

  pub fn with_managed_by(mut self, managed_by: String) -> IdentitySpec {
    self.managed_by = Some(managed_by);
    self
  }

  pub fn managed_by(&self) -> Option<&String> {
    self.managed_by.as_ref()
  }

  pub fn reset_managed_by(&mut self) {
    self.managed_by = None;
  }

}



