/* 
 * Identity Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-02-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct KeyPairSpec {
  /// An application tag associated with the key.
  #[serde(rename = "tag")]
  tag: String,
  #[serde(rename = "algo")]
  algo: String
}

impl KeyPairSpec {
  pub fn new(tag: String, algo: String) -> KeyPairSpec {
    KeyPairSpec {
      tag: tag,
      algo: algo
    }
  }

  pub fn set_tag(&mut self, tag: String) {
    self.tag = tag;
  }

  pub fn with_tag(mut self, tag: String) -> KeyPairSpec {
    self.tag = tag;
    self
  }

  pub fn tag(&self) -> &String {
    &self.tag
  }


  pub fn set_algo(&mut self, algo: String) {
    self.algo = algo;
  }

  pub fn with_algo(mut self, algo: String) -> KeyPairSpec {
    self.algo = algo;
    self
  }

  pub fn algo(&self) -> &String {
    &self.algo
  }


}



