/* 
 * Identity Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-02-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SignRequest {
  /// Sign algorithm to be used.
  #[serde(rename = "algo")]
  algo: String,
  /// Data to be signed.
  #[serde(rename = "data")]
  data: String
}

impl SignRequest {
  pub fn new(algo: String, data: String) -> SignRequest {
    SignRequest {
      algo: algo,
      data: data
    }
  }

  pub fn set_algo(&mut self, algo: String) {
    self.algo = algo;
  }

  pub fn with_algo(mut self, algo: String) -> SignRequest {
    self.algo = algo;
    self
  }

  pub fn algo(&self) -> &String {
    &self.algo
  }


  pub fn set_data(&mut self, data: String) {
    self.data = data;
  }

  pub fn with_data(mut self, data: String) -> SignRequest {
    self.data = data;
    self
  }

  pub fn data(&self) -> &String {
    &self.data
  }


}



